# Generated by Django 3.1.7 on 2021-03-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210330_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
