# Generated by Django 3.1.7 on 2021-03-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
